/**
 * List of markers. Markers are 3D visual objects in the world.
 *
 * See native [DRAW_MARKER](https://runtime.fivem.net/doc/natives/#_0x28477EC23D892089) for pictures.
 */
enum MarkerType {
  UpsideDownCone,
  VerticalCylinder,
  ThickChevronUp,
  ThinChevronUp,
  CheckeredFlagRect,
  CheckeredFlagCircle,
  VerticleCircle,
  PlaneModel,
  LostMCDark,
  LostMCLight,
  Number0,
  Number1,
  Number2,
  Number3,
  Number4,
  Number5,
  Number6,
  Number7,
  Number8,
  Number9,
  ChevronUpx1,
  ChevronUpx2,
  ChevronUpx3,
  HorizontalCircleFat,
  ReplayIcon,
  HorizontalCircleSkinny,
  HorizontalCircleSkinnyArrow,
  HorizontalSplitArrowCircle,
  DebugSphere,
  DollarSign,
  HorizontalBars,
  WolfHead,
  QuestionMark,
  PlaneSymbol,
  HelicopterSymbol,
  BoatSymbol,
  CarSymbol,
  MotorcycleSymbol,
  BikeSymbol,
  TruckSymbol,
  ParachuteSymbol,
  SawbladeSymbol,
}

export default MarkerType;
