export enum RadioStation {
  LosSantosRockRadio = 'RADIO_01_CLASS_ROCK',
  NonStopPopFM = 'RADIO_02_POP',
  RadioLosSantos = 'RADIO_03_HIPHOP_NEW',
  ChannelX = 'RADIO_04_PUNK',
  WestCoastTalkRadio = 'RADIO_05_TALK_01',
  RebelRadio = 'RADIO_06_COUNTRY',
  SoulwaxFM = 'RADIO_07_DANCE_01',
  EastLosFM = 'RADIO_08_MEXICAN',
  WestCoastClassics = 'RADIO_09_HIPHOP_OLD',
  BlaineCountyRadio = 'RADIO_11_TALK_02',
  TheBlueArk = 'RADIO_12_REGGAE',
  WorldWideFM = 'RADIO_13_JAZZ',
  FlyloFM = 'RADIO_14_DANCE_02',
  TheLowdown = 'RADIO_15_MOTOWN',
  RadioMirrorPark = 'RADIO_16_SILVERLAKE',
  Space = 'RADIO_17_FUNK',
  VinewoodBoulevardRadio = 'RADIO_18_90S_ROCK',
  SelfRadio = 'RADIO_19_USER',
  TheLab = 'RADIO_20_THELAB',
  BlondedLosSantos = 'RADIO_21_DLC_XM17',
  LosSantosUndergroundRadio = 'RADIO_22_DLC_BATTLE_MIX1_RADIO',
  RadioOff = 'OFF',
}
