export enum CargobobHook {
  Hook,
  Magnet,
}

export enum LicensePlateStyle {
  BlueOnWhite1 = 3,
  BlueOnWhite2 = 0,
  BlueOnWhite3 = 4,
  YellowOnBlack = 1,
  YellowOnBlue = 2,
  NorthYankton = 5,
}

export enum LicensePlateType {
  FrontAndRearPlates,
  FrontPlate,
  RearPlate,
  None,
}

export enum VehicleClass {
  Compacts,
  Sedans,
  SUVs,
  Coupes,
  Muscle,
  SportsClassics,
  Sports,
  Super,
  Motorcycles,
  OffRoad,
  Industrial,
  Utility,
  Vans,
  Cycles,
  Boats,
  Helicopters,
  Planes,
  Service,
  Emergency,
  Military,
  Commercial,
  Trains,
}

export enum VehicleColor {
  MetallicBlack,
  MetallicGraphiteBlack,
  MetallicBlackSteel,
  MetallicDarkSilver,
  MetallicSilver,
  MetallicBlueSilver,
  MetallicSteelGray,
  MetallicShadowSilver,
  MetallicStoneSilver,
  MetallicMidnightSilver,
  MetallicGunMetal,
  MetallicAnthraciteGray,
  MatteBlack,
  MatteGray,
  MatteLightGray,
  UtilBlack,
  UtilBlackPoly,
  UtilDarksilver,
  UtilSilver,
  UtilGunMetal,
  UtilShadowSilver,
  WornBlack,
  WornGraphite,
  WornSilverGray,
  WornSilver,
  WornBlueSilver,
  WornShadowSilver,
  MetallicRed,
  MetallicTorinoRed,
  MetallicFormulaRed,
  MetallicBlazeRed,
  MetallicGracefulRed,
  MetallicGarnetRed,
  MetallicDesertRed,
  MetallicCabernetRed,
  MetallicCandyRed,
  MetallicSunriseOrange,
  MetallicClassicGold,
  MetallicOrange,
  MatteRed,
  MatteDarkRed,
  MatteOrange,
  MatteYellow,
  UtilRed,
  UtilBrightRed,
  UtilGarnetRed,
  WornRed,
  WornGoldenRed,
  WornDarkRed,
  MetallicDarkGreen,
  MetallicRacingGreen,
  MetallicSeaGreen,
  MetallicOliveGreen,
  MetallicGreen,
  MetallicGasolineBlueGreen,
  MatteLimeGreen,
  UtilDarkGreen,
  UtilGreen,
  WornDarkGreen,
  WornGreen,
  WornSeaWash,
  MetallicMidnightBlue,
  MetallicDarkBlue,
  MetallicSaxonyBlue,
  MetallicBlue,
  MetallicMarinerBlue,
  MetallicHarborBlue,
  MetallicDiamondBlue,
  MetallicSurfBlue,
  MetallicNauticalBlue,
  MetallicBrightBlue,
  MetallicPurpleBlue,
  MetallicSpinnakerBlue,
  MetallicUltraBlue,
  UtilDarkBlue = 75,
  UtilMidnightBlue,
  UtilBlue,
  UtilSeaFoamBlue,
  UtilLightningBlue,
  UtilMauiBluePoly,
  UtilBrightBlue,
  MatteDarkBlue,
  MatteBlue,
  MatteMidnightBlue,
  WornDarkBlue,
  WornBlue,
  WornLightBlue,
  MetallicTaxiYellow,
  MetallicRaceYellow,
  MetallicBronze,
  MetallicYellowBird,
  MetallicLime,
  MetallicChampagne,
  MetallicPuebloBeige,
  MetallicDarkIvory,
  MetallicChocoBrown,
  MetallicGoldenBrown,
  MetallicLightBrown,
  MetallicStrawBeige,
  MetallicMossBrown,
  MetallicBistonBrown,
  MetallicBeechwood,
  MetallicDarkBeechwood,
  MetallicChocoOrange,
  MetallicBeachSand,
  MetallicSunBleechedSand,
  MetallicCream,
  UtilBrown,
  UtilMediumBrown,
  UtilLightBrown,
  MetallicWhite,
  MetallicFrostWhite,
  WornHoneyBeige,
  WornBrown,
  WornDarkBrown,
  WornStrawBeige,
  BrushedSteel,
  BrushedBlackSteel,
  BrushedAluminium,
  Chrome,
  WornOffWhite,
  UtilOffWhite,
  WornOrange,
  WornLightOrange,
  MetallicSecuricorGreen,
  WornTaxiYellow,
  PoliceCarBlue,
  MatteGreen,
  MatteBrown,
  MatteWhite = 131,
  WornWhite,
  WornOliveArmyGreen,
  PureWhite,
  HotPink,
  Salmonpink,
  MetallicVermillionPink,
  Orange,
  Green,
  Blue,
  MettalicBlackBlue,
  MetallicBlackPurple,
  MetallicBlackRed,
  HunterGreen,
  MetallicPurple,
  MetaillicVDarkBlue,
  ModshopBlack1,
  MattePurple,
  MatteDarkPurple,
  MetallicLavaRed,
  MatteForestGreen,
  MatteOliveDrab,
  MatteDesertBrown,
  MatteDesertTan,
  MatteFoliageGreen,
  DefaultAlloyColor,
  EpsilonBlue,
  PureGold,
  BrushedGold,
}

export enum VehicleLandingGearState {
  Deployed,
  Closing,
  Opening,
  Retracted,
}

export enum VehicleLockStatus {
  None,
  Unlocked,
  Locked,
  LockedForPlayer,
  StickPlayerInside,
  CanBeBrokenInto = 7,
  CanBeBrokenIntoPersist,
  CannotBeTriedToEnter = 10,
}

export enum VehicleNeonLight {
  Left,
  Right,
  Front,
  Back,
}

export enum VehicleRoofState {
  Closed,
  Opening,
  Opened,
  Closing,
}

export enum VehicleSeat {
  None = -3,
  Any,
  Driver,
  Passenger,
  LeftFront = -1,
  RightFront,
  LeftRear,
  RightRear,
  ExtraSeat1,
  ExtraSeat2,
  ExtraSeat3,
  ExtraSeat4,
  ExtraSeat5,
  ExtraSeat6,
  ExtraSeat7,
  ExtraSeat8,
  ExtraSeat9,
  ExtraSeat10,
  ExtraSeat11,
  ExtraSeat12,
}

export enum VehicleWindowTint {
  None,
  PureBlack,
  DarkSmoke,
  LightSmoke,
  Stock,
  Limo,
  Green,
}

export enum VehicleWindowIndex {
  FrontRightWindow = 1,
  FrontLeftWindow = 0,
  BackRightWindow = 3,
  BackLeftWindow = 2,
  ExtraWindow1 = 4,
  ExtraWindow2 = 5,
  ExtraWindow3 = 6,
  ExtraWindow4 = 7,
}

export enum VehicleModType {
  Spoilers,
  FrontBumper,
  RearBumper,
  SideSkirt,
  Exhaust,
  Frame,
  Grille,
  Hood,
  Fender,
  RightFender,
  Roof,
  Engine,
  Brakes,
  Transmission,
  Horns,
  Suspension,
  Armor,
  FrontWheel = 23,
  RearWheel,
  PlateHolder,
  VanityPlates,
  TrimDesign,
  Ornaments,
  Dashboard,
  DialDesign,
  DoorSpeakers,
  Seats,
  SteeringWheels,
  ColumnShifterLevers,
  Plaques,
  Speakers,
  Trunk,
  Hydraulics,
  EngineBlock,
  AirFilter,
  Struts,
  ArchCover,
  Aerials,
  Trim,
  Tank,
  Windows,
  Livery = 48,
}

export enum VehicleToggleModType {
  Turbo = 18,
  TireSmoke = 20,
  XenonHeadlights = 22,
}

export enum VehiclePaintType {
  Normal,
  Metallic,
  Pearl,
  Matte,
  Metal,
  Chrome,
}

export enum VehicleDoorIndex {
  FrontRightDoor = 1,
  FrontLeftDoor = 0,
  BackRightDoor = 3,
  BackLeftDoor = 2,
  Hood = 4,
  Trunk = 5,
}

export enum VehicleWheelType {
  Sport,
  Muscle,
  Lowrider,
  SUV,
  Offroad,
  Tuner,
  BikeWheels,
  HighEnd,
  BennysOriginals,
  BennysBespoke,
}

export enum VehicleWheelIndex {
  FrontLeftWheel,
  FrontRightWheel,
  MidLeftWheel,
  MidRightWheel,
  RearLeftWheel,
  RearRightWheel,
  TrailerMidLeftWheel = 45,
  TrailerMidRightWheel = 47,
}
