import { WeaponHash } from '../hashes';
import { WeaponComponentHash } from './WeaponComponentHash';

/**
 * Mapping of WeaponHash -> WeaponComponentHashes,
 * use for
 *
 */
export const WeaponComponentHashesByWeaponHash = new Map<WeaponHash, WeaponComponentHash[]>([
  [
    WeaponHash.Pistol,
    [
      WeaponComponentHash.PistolClip01,
      WeaponComponentHash.PistolClip02,
      WeaponComponentHash.AtPiFlsh,
      WeaponComponentHash.AtPiSupp02,
      WeaponComponentHash.PistolVarmodLuxe,
    ],
  ],
  [
    WeaponHash.CombatPistol,
    [
      WeaponComponentHash.CombatPistolClip01,
      WeaponComponentHash.CombatPistolClip02,
      WeaponComponentHash.AtPiFlsh,
      WeaponComponentHash.AtPiSupp,
      WeaponComponentHash.CombatPistolVarmodLowrider,
    ],
  ],
  [
    WeaponHash.APPistol,
    [
      WeaponComponentHash.APPistolClip01,
      WeaponComponentHash.APPistolClip02,
      WeaponComponentHash.AtPiFlsh,
      WeaponComponentHash.AtPiSupp,
      WeaponComponentHash.APPistolVarmodLuxe,
    ],
  ],
  [
    WeaponHash.MicroSMG,
    [
      WeaponComponentHash.MicroSMGClip01,
      WeaponComponentHash.MicroSMGClip02,
      WeaponComponentHash.AtPiFlsh,
      WeaponComponentHash.AtScopeMacro,
      WeaponComponentHash.AtArSupp02,
      WeaponComponentHash.MicroSMGVarmodLuxe,
    ],
  ],
  [
    WeaponHash.SMG,
    [
      WeaponComponentHash.SMGClip01,
      WeaponComponentHash.SMGClip02,
      WeaponComponentHash.SMGClip03,
      WeaponComponentHash.AtArFlsh,
      WeaponComponentHash.AtPiSupp,
      WeaponComponentHash.AtScopeMacro02,
      WeaponComponentHash.AtArAfGrip,
      WeaponComponentHash.SMGVarmodLuxe,
    ],
  ],
  [
    WeaponHash.AssaultRifle,
    [
      WeaponComponentHash.AssaultRifleClip01,
      WeaponComponentHash.AssaultRifleClip02,
      WeaponComponentHash.AssaultRifleClip03,
      WeaponComponentHash.AtArAfGrip,
      WeaponComponentHash.AtArFlsh,
      WeaponComponentHash.AtScopeMacro,
      WeaponComponentHash.AtArSupp02,
      WeaponComponentHash.AssaultRifleVarmodLuxe,
    ],
  ],
  [
    WeaponHash.CarbineRifle,
    [
      WeaponComponentHash.CarbineRifleClip01,
      WeaponComponentHash.CarbineRifleClip02,
      WeaponComponentHash.CarbineRifleClip03,
      WeaponComponentHash.AtRailCover01,
      WeaponComponentHash.AtArAfGrip,
      WeaponComponentHash.AtArFlsh,
      WeaponComponentHash.AtScopeMedium,
      WeaponComponentHash.AtArSupp,
      WeaponComponentHash.CarbineRifleVarmodLuxe,
    ],
  ],
  [
    WeaponHash.AdvancedRifle,
    [
      WeaponComponentHash.AdvancedRifleClip01,
      WeaponComponentHash.AdvancedRifleClip02,
      WeaponComponentHash.AtArFlsh,
      WeaponComponentHash.AtScopeSmall,
      WeaponComponentHash.AtArSupp,
      WeaponComponentHash.AdvancedRifleVarmodLuxe,
    ],
  ],
  [
    WeaponHash.MG,
    [
      WeaponComponentHash.MGClip01,
      WeaponComponentHash.MGClip02,
      WeaponComponentHash.AtScopeSmall02,
      WeaponComponentHash.AtArAfGrip,
      WeaponComponentHash.MGVarmodLowrider,
    ],
  ],
  [
    WeaponHash.CombatMG,
    [
      WeaponComponentHash.CombatMGClip01,
      WeaponComponentHash.CombatMGClip02,
      WeaponComponentHash.AtArAfGrip,
      WeaponComponentHash.AtScopeMedium,
      WeaponComponentHash.CombatMGVarmodLowrider,
    ],
  ],
  [
    WeaponHash.PumpShotgun,
    [
      WeaponComponentHash.AtSrSupp,
      WeaponComponentHash.AtArFlsh,
      WeaponComponentHash.PumpShotgunVarmodLowrider,
    ],
  ],
  [
    WeaponHash.AssaultShotgun,
    [
      WeaponComponentHash.AssaultShotgunClip01,
      WeaponComponentHash.AssaultShotgunClip02,
      WeaponComponentHash.AtArAfGrip,
      WeaponComponentHash.AtArFlsh,
      WeaponComponentHash.AtArSupp,
    ],
  ],
  [
    WeaponHash.SniperRifle,
    [
      WeaponComponentHash.SniperRifleClip01,
      WeaponComponentHash.AtScopeLarge,
      WeaponComponentHash.AtScopeMax,
      WeaponComponentHash.AtArSupp02,
      WeaponComponentHash.SniperRifleVarmodLuxe,
    ],
  ],
  [
    WeaponHash.HeavySniper,
    [
      WeaponComponentHash.HeavySniperClip01,
      WeaponComponentHash.AtScopeLarge,
      WeaponComponentHash.AtScopeMax,
    ],
  ],
  [
    WeaponHash.GrenadeLauncher,
    [
      WeaponComponentHash.AtArAfGrip,
      WeaponComponentHash.AtArFlsh,
      WeaponComponentHash.AtScopeSmall,
    ],
  ],
  [
    WeaponHash.Minigun,
    [
      WeaponComponentHash.MinigunClip01,
    ],
  ],
  [
    WeaponHash.AssaultSMG,
    [
      WeaponComponentHash.AssaultSMGClip01,
      WeaponComponentHash.AssaultSMGClip02,
      WeaponComponentHash.AtArFlsh,
      WeaponComponentHash.AtScopeMacro,
      WeaponComponentHash.AtArSupp02,
      WeaponComponentHash.AssaultSMGVarmodLowrider,
    ],
  ],
  [
    WeaponHash.BullpupShotgun,
    [
      WeaponComponentHash.AtArAfGrip,
      WeaponComponentHash.AtArFlsh,
      WeaponComponentHash.AtArSupp02,
    ],
  ],
  [
    WeaponHash.Pistol50,
    [
      WeaponComponentHash.Pistol50Clip01,
      WeaponComponentHash.Pistol50Clip02,
      WeaponComponentHash.AtPiFlsh,
      WeaponComponentHash.AtArSupp02,
      WeaponComponentHash.Pistol50VarmodLuxe,
    ],
  ],
  [
    WeaponHash.CombatPDW,
    [
      WeaponComponentHash.CombatPDWClip01,
      WeaponComponentHash.CombatPDWClip02,
      WeaponComponentHash.CombatPDWClip03,
      WeaponComponentHash.AtArFlsh,
      WeaponComponentHash.AtScopeSmall,
      WeaponComponentHash.AtArAfGrip,
    ],
  ],
  [
    WeaponHash.SawnOffShotgun,
    [
      WeaponComponentHash.SawnoffShotgunVarmodLuxe,
    ],
  ],
  [
    WeaponHash.BullpupRifle,
    [
      WeaponComponentHash.BullpupRifleClip01,
      WeaponComponentHash.BullpupRifleClip02,
      WeaponComponentHash.AtArFlsh,
      WeaponComponentHash.AtScopeSmall,
      WeaponComponentHash.AtArSupp,
      WeaponComponentHash.AtArAfGrip,
      WeaponComponentHash.BullpupRifleVarmodLow,
    ],
  ],
  [
    WeaponHash.SNSPistol,
    [
      WeaponComponentHash.SNSPistolClip01,
      WeaponComponentHash.SNSPistolClip02,
      WeaponComponentHash.SNSPistolVarmodLowrider,
    ],
  ],
  [
    WeaponHash.SpecialCarbine,
    [
      WeaponComponentHash.SpecialCarbineClip01,
      WeaponComponentHash.SpecialCarbineClip02,
      WeaponComponentHash.SpecialCarbineClip03,
      WeaponComponentHash.AtArFlsh,
      WeaponComponentHash.AtScopeMedium,
      WeaponComponentHash.AtArSupp02,
      WeaponComponentHash.AtArAfGrip,
      WeaponComponentHash.SpecialCarbineVarmodLowrider,
    ],
  ],
  [
    WeaponHash.KnuckleDuster,
    [
      WeaponComponentHash.KnuckleVarmodPimp,
      WeaponComponentHash.KnuckleVarmodBallas,
      WeaponComponentHash.KnuckleVarmodDollar,
      WeaponComponentHash.KnuckleVarmodDiamond,
      WeaponComponentHash.KnuckleVarmodHate,
      WeaponComponentHash.KnuckleVarmodLove,
      WeaponComponentHash.KnuckleVarmodPlayer,
      WeaponComponentHash.KnuckleVarmodKing,
      WeaponComponentHash.KnuckleVarmodVagos,
    ],
  ],
  [
    WeaponHash.MachinePistol,
    [
      WeaponComponentHash.MachinePistolClip01,
      WeaponComponentHash.MachinePistolClip02,
      WeaponComponentHash.MachinePistolClip03,
      WeaponComponentHash.AtPiSupp,
    ],
  ],
  [
    WeaponHash.SwitchBlade,
    [
      WeaponComponentHash.SwitchbladeVarmodVar1,
      WeaponComponentHash.SwitchbladeVarmodVar2,
    ],
  ],
  [
    WeaponHash.Revolver,
    [
      WeaponComponentHash.RevolverClip01,
      WeaponComponentHash.RevolverVarmodBoss,
      WeaponComponentHash.RevolverVarmodGoon,
    ],
  ],
  // GUNRUNNING
  [
    WeaponHash.PistolMk2,
    [
      WeaponComponentHash.PistolMk2ClipNormal,
      WeaponComponentHash.PistolMk2ClipExtended,
      WeaponComponentHash.PistolMk2ClipFMJ,
      WeaponComponentHash.PistolMk2ClipHollowpoint,
      WeaponComponentHash.PistolMk2ClipIncendiary,
      WeaponComponentHash.PistolMk2ClipTracer,
      WeaponComponentHash.PistolMk2Scope,
      WeaponComponentHash.PistolMk2Flash,
      WeaponComponentHash.AtPiSupp02,
      WeaponComponentHash.PistolMk2Compensator,
      WeaponComponentHash.PistolMk2CamoDigital,
      WeaponComponentHash.PistolMk2CamoBrushstroke,
      WeaponComponentHash.PistolMk2CamoWoodland,
      WeaponComponentHash.PistolMk2CamoSkull,
      WeaponComponentHash.PistolMk2CamoSessanta,
      WeaponComponentHash.PistolMk2CamoPerseus,
      WeaponComponentHash.PistolMk2CamoLeopard,
      WeaponComponentHash.PistolMk2CamoZebra,
      WeaponComponentHash.PistolMk2CamoGeometric,
      WeaponComponentHash.PistolMk2CamoBoom,
      WeaponComponentHash.PistolMk2CamoPatriotic,
      WeaponComponentHash.PistolMk2CamoSlideDigital,
      WeaponComponentHash.PistolMk2CamoSlideBrushstroke,
      WeaponComponentHash.PistolMk2CamoSlideWoodland,
      WeaponComponentHash.PistolMk2CamoSlideSkull,
      WeaponComponentHash.PistolMk2CamoSlideSessanta,
      WeaponComponentHash.PistolMk2CamoSlidePerseus,
      WeaponComponentHash.PistolMk2CamoSlideLeopard,
      WeaponComponentHash.PistolMk2CamoSlideZebra,
      WeaponComponentHash.PistolMk2CamoSlideGeometric,
      WeaponComponentHash.PistolMk2CamoSlideBoom,
      WeaponComponentHash.PistolMk2CamoSlidePatriotic,
    ],
  ],
  [
    WeaponHash.AssaultRifleMk2,
    [
      WeaponComponentHash.AssaultRifleMk2ClipNormal,
      WeaponComponentHash.AssaultRifleMk2ClipExtended,
      WeaponComponentHash.AssaultRifleMk2ClipArmorPiercing,
      WeaponComponentHash.AssaultRifleMk2ClipFMJ,
      WeaponComponentHash.AssaultRifleMk2ClipIncendiary,
      WeaponComponentHash.AssaultRifleMk2ClipTracer,
      WeaponComponentHash.AtArFlsh,
      WeaponComponentHash.AtSights,
      WeaponComponentHash.AtScopeMacroMk2,
      WeaponComponentHash.AtScopeMediumMk2,
      WeaponComponentHash.AtArSupp02,
      WeaponComponentHash.AtMuzzle1,
      WeaponComponentHash.AtMuzzle2,
      WeaponComponentHash.AtMuzzle3,
      WeaponComponentHash.AtMuzzle4,
      WeaponComponentHash.AtMuzzle5,
      WeaponComponentHash.AtMuzzle6,
      WeaponComponentHash.AtMuzzle7,
      WeaponComponentHash.AtArAfGrip2,
      WeaponComponentHash.AssaultRifleMk2BarrelNormal,
      WeaponComponentHash.AssaultRifleMk2BarrelHeavy,
      WeaponComponentHash.AssaultRifleMk2CamoDigital,
      WeaponComponentHash.AssaultRifleMk2CamoBrushstroke,
      WeaponComponentHash.AssaultRifleMk2CamoWoodland,
      WeaponComponentHash.AssaultRifleMk2CamoSkull,
      WeaponComponentHash.AssaultRifleMk2CamoSessanta,
      WeaponComponentHash.AssaultRifleMk2CamoPerseus,
      WeaponComponentHash.AssaultRifleMk2CamoLeopard,
      WeaponComponentHash.AssaultRifleMk2CamoZebra,
      WeaponComponentHash.AssaultRifleMk2CamoGeometric,
      WeaponComponentHash.AssaultRifleMk2CamoBoom,
      WeaponComponentHash.AssaultRifleMk2CamoPatriotic,
    ],
  ],
  [
    WeaponHash.CarbineRifleMk2,
    [
      WeaponComponentHash.CarbineRifleMk2ClipNormal,
      WeaponComponentHash.CarbineRifleMk2ClipExtended,
      WeaponComponentHash.CarbineRifleMk2ClipArmorPiercing,
      WeaponComponentHash.CarbineRifleMk2ClipFMJ,
      WeaponComponentHash.CarbineRifleMk2ClipIncendiary,
      WeaponComponentHash.CarbineRifleMk2ClipTracer,
      WeaponComponentHash.AtSights,
      WeaponComponentHash.AtScopeMacroMk2,
      WeaponComponentHash.AtScopeMediumMk2,
      WeaponComponentHash.AtArAfGrip2,
      WeaponComponentHash.CarbineRifleMk2BarrelNormal,
      WeaponComponentHash.CarbineRifleMk2BarrelHeavy,
      WeaponComponentHash.AtArSupp,
      WeaponComponentHash.AtMuzzle1,
      WeaponComponentHash.AtMuzzle2,
      WeaponComponentHash.AtMuzzle3,
      WeaponComponentHash.AtMuzzle4,
      WeaponComponentHash.AtMuzzle5,
      WeaponComponentHash.AtMuzzle6,
      WeaponComponentHash.AtMuzzle7,
      WeaponComponentHash.CarbineRifleMk2CamoDigital,
      WeaponComponentHash.CarbineRifleMk2CamoBrushstroke,
      WeaponComponentHash.CarbineRifleMk2CamoWoodland,
      WeaponComponentHash.CarbineRifleMk2CamoSkull,
      WeaponComponentHash.CarbineRifleMk2CamoSessanta,
      WeaponComponentHash.CarbineRifleMk2CamoPerseus,
      WeaponComponentHash.CarbineRifleMk2CamoLeopard,
      WeaponComponentHash.CarbineRifleMk2CamoZebra,
      WeaponComponentHash.CarbineRifleMk2CamoGeometric,
      WeaponComponentHash.CarbineRifleMk2CamoBoom,
      WeaponComponentHash.CarbineRifleMk2CamoPatriotic,
    ],
  ],
  [
    WeaponHash.CombatMGMk2,
    [
      WeaponComponentHash.CombatMGMk2ClipNormal,
      WeaponComponentHash.CombatMGMk2ClipExtended,
      WeaponComponentHash.CombatMGMk2ClipArmorPiercing,
      WeaponComponentHash.CombatMGMk2ClipFMJ,
      WeaponComponentHash.CombatMGMk2ClipIncendiary,
      WeaponComponentHash.CombatMGMk2ClipTracer,
      WeaponComponentHash.AtSights,
      WeaponComponentHash.AtScopeSmallMk2,
      WeaponComponentHash.AtScopeMediumMk2,
      WeaponComponentHash.AtMuzzle1,
      WeaponComponentHash.AtMuzzle2,
      WeaponComponentHash.AtMuzzle3,
      WeaponComponentHash.AtMuzzle4,
      WeaponComponentHash.AtMuzzle5,
      WeaponComponentHash.AtMuzzle6,
      WeaponComponentHash.AtMuzzle7,
      WeaponComponentHash.AtArAfGrip2,
      WeaponComponentHash.CombatMGMk2BarrelNormal,
      WeaponComponentHash.CombatMGMk2BarrelHeavy,
      WeaponComponentHash.CombatMGMk2CamoDigital,
      WeaponComponentHash.CombatMGMk2CamoBrushstroke,
      WeaponComponentHash.CombatMGMk2CamoWoodland,
      WeaponComponentHash.CombatMGMk2CamoSkull,
      WeaponComponentHash.CombatMGMk2CamoSessanta,
      WeaponComponentHash.CombatMGMk2CamoPerseus,
      WeaponComponentHash.CombatMGMk2CamoLeopard,
      WeaponComponentHash.CombatMGMk2CamoZebra,
      WeaponComponentHash.CombatMGMk2CamoGeometric,
      WeaponComponentHash.CombatMGMk2CamoBoom,
      WeaponComponentHash.CombatMGMk2CamoPatriotic,
    ],
  ],
  [
    WeaponHash.HeavySniperMk2,
    [
      WeaponComponentHash.HeavySniperMk2ClipNormal,
      WeaponComponentHash.HeavySniperMk2ClipExtended,
      WeaponComponentHash.HeavySniperMk2ClipArmorPiercing,
      WeaponComponentHash.HeavySniperMk2ClipExplosive,
      WeaponComponentHash.HeavySniperMk2ClipFMJ,
      WeaponComponentHash.HeavySniperMk2ClipIncendiary,
      WeaponComponentHash.HeavySniperMk2ScopeLarge,
      WeaponComponentHash.AtScopeMax,
      WeaponComponentHash.HeavySniperMk2ScopeNightvision,
      WeaponComponentHash.HeavySniperMk2ScopeThermal,
      WeaponComponentHash.HeavySniperMk2Suppressor,
      WeaponComponentHash.HeavySniperMk2Muzzle8,
      WeaponComponentHash.HeavySniperMk2Muzzle9,
      WeaponComponentHash.HeavySniperMk2BarrelNormal,
      WeaponComponentHash.HeavySniperMk2BarrelHeavy,
      WeaponComponentHash.HeavySniperMk2CamoDigital,
      WeaponComponentHash.HeavySniperMk2CamoBrushstroke,
      WeaponComponentHash.HeavySniperMk2CamoWoodland,
      WeaponComponentHash.HeavySniperMk2CamoSkull,
      WeaponComponentHash.HeavySniperMk2CamoSessanta,
      WeaponComponentHash.HeavySniperMk2CamoPerseus,
      WeaponComponentHash.HeavySniperMk2CamoLeopard,
      WeaponComponentHash.HeavySniperMk2CamoZebra,
      WeaponComponentHash.HeavySniperMk2CamoGeometric,
      WeaponComponentHash.HeavySniperMk2CamoBoom,
      WeaponComponentHash.HeavySniperMk2CamoPatriotic,
    ],
  ],
  [
    WeaponHash.SMGMk2,
    [
      WeaponComponentHash.SMGMk2ClipNormal,
      WeaponComponentHash.SMGMk2ClipExtended,
      WeaponComponentHash.SMGMk2ClipFMJ,
      WeaponComponentHash.SMGMk2ClipHollowpoint,
      WeaponComponentHash.SMGMk2ClipIncendiary,
      WeaponComponentHash.SMGMk2ClipTracer,
      WeaponComponentHash.AtArFlsh,
      WeaponComponentHash.SMGMk2Sights,
      WeaponComponentHash.SMGMk2ScopeMacro,
      WeaponComponentHash.SMGMk2ScopeSmall,
      WeaponComponentHash.AtPiSupp,
      WeaponComponentHash.SMGMk2BarrelNormal,
      WeaponComponentHash.SMGMk2BarrelHeavy,
      WeaponComponentHash.AtMuzzle1,
      WeaponComponentHash.AtMuzzle2,
      WeaponComponentHash.AtMuzzle3,
      WeaponComponentHash.AtMuzzle4,
      WeaponComponentHash.AtMuzzle5,
      WeaponComponentHash.AtMuzzle6,
      WeaponComponentHash.AtMuzzle7,
      WeaponComponentHash.SMGMk2CamoDigital,
      WeaponComponentHash.SMGMk2CamoBrushstroke,
      WeaponComponentHash.SMGMk2CamoWoodland,
      WeaponComponentHash.SMGMk2CamoSkull,
      WeaponComponentHash.SMGMk2CamoSessanta,
      WeaponComponentHash.SMGMk2CamoPerseus,
      WeaponComponentHash.SMGMk2CamoLeopard,
      WeaponComponentHash.SMGMk2CamoZebra,
      WeaponComponentHash.SMGMk2CamoGeometric,
      WeaponComponentHash.SMGMk2CamoBoom,
      WeaponComponentHash.SMGMk2CamoPatriotic,
    ],
  ],
]);

/**
 * Initialize dlc data, avoid calling expansive native repeatedly
 *
 */
function initializeDlcDataOnce() {
  let isInitialized = false;

  return function() {
    if (isInitialized) {
      return;
    }

    // magic number based on struct DlcWeaponData
    const intLength = 4;
    const strLength = 64;

    const weaponCount = GetNumDlcWeapons();
    for (let i = 0; i < weaponCount; i++) {
      const weaponBuffer = new Uint8Array(14 * intLength + 4 * strLength);

      // https://docs.fivem.net/natives/?_0x79923CD21BECE14E
      Citizen.invokeNative('0x79923CD21BECE14E', i, weaponBuffer, Citizen.returnResultAnyway());

      const weaponHash = new Uint32Array(weaponBuffer.slice(2 * intLength, 3 * intLength).buffer)[0];

      const componentCount = GetNumDlcWeaponComponents(i);

      const componentHashes: WeaponComponentHash[] = [];
      for (let j = 0; j < componentCount; j++) {
        const componentBuffer = new Uint8Array(14 * intLength + 4 * strLength);

        // https://docs.fivem.net/natives/?_0x6CF598A2957C2BF8
        Citizen.invokeNative('0x6CF598A2957C2BF8', i, j, componentBuffer, Citizen.returnResultAnyway());

        const componentHash = new Uint32Array(componentBuffer.slice(6 * intLength, 7 * intLength).buffer)[0];
        componentHashes.push(componentHash);
      }

      WeaponComponentHashesByWeaponHash.set(weaponHash, componentHashes);
    }

    isInitialized = true;
  };
}

initializeDlcDataOnce();
