import { Model } from './Model';
import { Ped } from './models/Ped';
import { Vehicle } from './models/Vehicle';
import { Color } from './utils/Color';
import { Vector3 } from './utils/Math';

export enum ZoneID {
  AIRP,
  ALAMO,
  ALTA,
  ARMYB,
  BANHAMC,
  BANNING,
  BEACH,
  BHAMCA,
  BRADP,
  BRADT,
  BURTON,
  CALAFB,
  CANNY,
  CCREAK,
  CHAMH,
  CHIL,
  CHU,
  CMSW,
  CYPRE,
  DAVIS,
  DELBE,
  DELPE,
  DELSOL,
  DESRT,
  DOWNT,
  DTVINE,
  EAST_V,
  EBURO,
  ELGORL,
  ELYSIAN,
  GALFISH,
  golf,
  GRAPES,
  GREATC,
  HARMO,
  HAWICK,
  HORS,
  HUMLAB,
  JAIL,
  KOREAT,
  LACT,
  LAGO,
  LDAM,
  LEGSQU,
  LMESA,
  LOSPUER,
  MIRR,
  MORN,
  MOVIE,
  MTCHIL,
  MTGORDO,
  MTJOSE,
  MURRI,
  NCHU,
  NOOSE,
  OCEANA,
  PALCOV,
  PALETO,
  PALFOR,
  PALHIGH,
  PALMPOW,
  PBLUFF,
  PBOX,
  PROCOB,
  RANCHO,
  RGLEN,
  RICHM,
  ROCKF,
  RTRAK,
  SanAnd,
  SANCHIA,
  SANDY,
  SKID,
  SLAB,
  STAD,
  STRAW,
  TATAMO,
  TERMINA,
  TEXTI,
  TONGVAH,
  TONGVAV,
  VCANA,
  VESP,
  VINE,
  WINDF,
  WVINE,
  ZANCUDO,
  ZP_ORT,
  ZQ_UAR,
}

export enum Weather {
  Unknown = -1,
  ExtraSunny,
  Clear,
  Clouds,
  Smog,
  Foggy,
  Overcast,
  Raining,
  ThunderStorm,
  Clearing,
  Neutral,
  Snowing,
  Blizzard,
  Snowlight,
  Christmas,
  Halloween,
}

export enum WeatherTypeHash {
  Unknown = -1,
  ExtraSunny = -1750463879,
  Clear = 916995460,
  Neutral = -1530260698,
  Smog = 282916021,
  Foggy = -1368164796,
  Clouds = 821931868,
  Overcast = -1148613331,
  Clearing = 1840358669,
  Raining = 1420204096,
  ThunderStorm = -1233681761,
  Blizzard = 669657108,
  Snowing = -273223690,
  Snowlight = 603685163,
  Christmas = -1429616491,
  Halloween = -921030142,
}

export enum CloudHat {
  Unknown = 1,
  Altostratus,
  Cirrus,
  Cirrocumulus,
  Clear,
  Cloudy,
  Contrails,
  Horizon,
  HorizonBand1,
  HorizonBand2,
  HorizonBand3,
  Horsey,
  Nimbus,
  Puffs,
  Rain,
  Snowy,
  Stormy,
  Stratoscumulus,
  Stripey,
  Shower,
  Wispy,
}

export enum IntersectOptions {
  Everything = -1,
  Map = 1,
  MissionEntities,
  Peds1 = 12,
  Objects = 16,
  Unk1 = 32,
  Unk2 = 64,
  Unk3 = 128,
  Vegetation = 256,
  Unk4 = 512,
}

export enum MarkerType {
  UpsideDownCone,
  VerticalCylinder,
  ThickChevronUp,
  ThinChevronUp,
  CheckeredFlagRect,
  CheckeredFlagCircle,
  VerticleCircle,
  PlaneModel,
  LostMCDark,
  LostMCLight,
  Number0,
  Number1,
  Number2,
  Number3,
  Number4,
  Number5,
  Number6,
  Number7,
  Number8,
  Number9,
  ChevronUpx1,
  ChevronUpx2,
  ChevronUpx3,
  HorizontalCircleFat,
  ReplayIcon,
  HorizontalCircleSkinny,
  HorizontalCircleSkinnyArrow,
  HorizontalSplitArrowCircle,
  DebugSphere,
  DollarSign,
  HorizontalBars,
  WolfHead,
  QuestionMark,
  PlaneSymbol,
  HelicopterSymbol,
  BoatSymbol,
  CarSymbol,
  MotorcycleSymbol,
  BikeSymbol,
  TruckSymbol,
  ParachuteSymbol,
  SawbladeSymbol,
}

export enum ExplosionType {
  Grenade,
  GrenadeL,
  StickyBomb,
  Molotov1,
  Rocket,
  TankShell,
  HiOctane,
  Car,
  Plane,
  PetrolPump,
  Bike,
  Steam,
  Flame,
  WaterHydrant,
  GasCanister,
  Boat,
  ShipDestroy,
  Truck,
  Bullet,
  SmokeGL,
  SmokeG,
  BZGas,
  Flare,
  GasCanister2,
  Extinguisher,
  ProgramAR,
  Train,
  Barrel,
  Propane,
  Blimp,
  FlameExplode,
  Tanker,
  PlaneRocket,
  VehicleBullet,
  GasTank,
  FireWork,
  SnowBall,
  ProxMine,
  Valkyrie,
}

export abstract class World {
  public static CreatePed(model: Model, position: Vector3, heading: number = 0): Promise<Ped> {
    return new Promise(async resolve => {
      if (!model.IsPed || !(await model.Request(1000))) {
        return null;
      }
      resolve(new Ped(CreatePed(26, model.Hash, position.x, position.y, position.z, heading, true, false)));
    });
  }

  public static CreateVehicle(model: Model, position: Vector3, heading: number = 0): Promise<Vehicle> {
    return new Promise(async resolve => {
      if (!model.IsPed || !(await model.Request(1000))) {
        return null;
      }
      resolve(new Vehicle(CreateVehicle(model.Hash, position.x, position.y, position.z, heading, true, false)));
    });
  }

  public static DrawMarker(
    type: MarkerType,
    position: Vector3,
    direction: Vector3,
    rotation: Vector3,
    scale: Vector3,
    color: Color,
    bobUpAndDown: boolean = false,
    faceCamera: boolean = false,
    rotateY: boolean = false,
    textureDict: string = null,
    textureName: string = null,
    drawOnEntity: boolean = false,
  ) {
    DrawMarker(
      Number(type),
      position.x,
      position.y,
      position.z,
      direction.x,
      direction.y,
      direction.z,
      rotation.x,
      rotation.y,
      rotation.z,
      scale.x,
      scale.y,
      scale.z,
      color.r,
      color.g,
      color.b,
      color.a,
      bobUpAndDown,
      faceCamera,
      2,
      rotateY,
      textureDict,
      textureName,
      drawOnEntity,
    );
  }
}
